<?php echo $this->doctype() ?>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <?php
        $title=$this->HomeHelper()->getIssusers('title');
        echo$this->headTitle("..::{$title}::")->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php 
        $setSeoFacebook=$this->HomeHelper()->setSeo('facebook');
        if($setSeoFacebook){
            $this->headMeta()->setProperty('fb:app_id', $setSeoFacebook->getAppId());

            $this->OpenGraph()->setType($setSeoFacebook->getType());

            $this->OpenGraph()->setTitle($setSeoFacebook->getTitle());

            $this->OpenGraph()->setSiteName($setSeoFacebook->getSiteName());

            $this->OpenGraph()->setDescription(\Base\Model\Check::Chars($setSeoFacebook->getDescription(),100));

            $this->OpenGraph()->setUrl($setSeoFacebook->getUrl());
            // $this->OpenGraph()->setLocale('pt', array('pt_BR', 'sr'));
            $this->OpenGraph()->prependImage(sprintf("%sdist/%s",$setSeoFacebook->getUrl(),$setSeoFacebook->getImages()));
        }
         echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1, maximum-scale=1')->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
        ?>

        <!-- Le styles -->
        <?php echo$this->headLink(['rel' => 'shortcut icon', 'type' => '/assets_admin/image/vnd.microsoft.icon', 'href' => $this->basePath() . '/assets_admin/img/favicon.ico'])
           
            ->prependStylesheet($this->basePath('/materialize_admin/css/font-awesome.min.css'))
            ->prependStylesheet('//fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic')
            ->prependStylesheet($this->basePath('/materialize_admin/css/materialize.min.css'))
        ?>
        <!-- <meta name="google-site-verification" content="EVvJ5qfhvH5HQx-mMgMK8Fh9kOis6TVkyoRbFs95ioY" /> -->
         <style type="text/css"></style>

    </head>
    
<?php //echo$this->partial('/partial/home-top')?>
<body id="app">
      <?php //echo $this->partial('/home/home/tpl/theme-options') ?>
<nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo right">Logo</a>
      <ul id="nav-mobile" class="left hide-on-med-and-down">
         <li><a href="/" title="Pagina Inicial">HOME</a></li>
        <li><a href="<?=$this->url('home/default',['controller'=>'home','action'=>'termos-de-uso'])?>" title="Termos De Uso">TERMOS DE USO</a></li>
        <li><a href="<?=$this->url('home/default',['controller'=>'home','action'=>'politica-de-privacidade'])?>" title="Politica De Privacidade">POLITICA DE PRIVACIDADE</a></li>
      </ul>
    </div>
  </nav>
    <div class="container">
       <?= $this->content ?>
      </div>
 <!--BEGIN-FOOTER-->
       <footer class="page-footer">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Footer Content</h5>
                <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                   <?php $Redesociais=$this->ReadHelper()->ExeRead('bs_rede_social',' WHERE state =? ORDER BY modified DESC LIMIT 12 OFFSET 0', ['0']);?>
                            <?php
                            $html=[];
                            if (!$Redesociais->getResult()):
                                $this->ReadHelper()->alert($Redesociais->getError());
                            else:
                                $url=['Twitter'=>'','LinkDin'=>'Google'];
                                foreach ($Redesociais->getData() as $Redesocial):
                                    $Redesocial['url']=sprintf("%s%s",$Redesocial['url'],$Redesocial['id_usuario']);
                                    $partial='<li><a  title="#title#" targat="_blank" href="#url#" class="waves-effect waves-circle waves-light btn-floating secondary-content"><i class="#icone#"></i></a></li>';
                                    $html[]=$this->ReadHelper()->Show($Redesocial, $partial,"redesociais");
                                endforeach;
                            endif;
                            echo implode("", $html);
                    ?>
                  
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            <div class="container">
                    
            © 2014 Copyright Text
            <a class="grey-text text-lighten-4 right" href="http://www.sigasmart.com.br">SIGA-SMART</a>
            </div>
          </div>
        </footer>

        
          
          <input type="hidden" id="lat" value="<?php echo $this->HomeHelper()->getIssusers('latitude');?>">
          <input type="hidden" id="long" value="<?php echo $this->HomeHelper()->getIssusers('longetude');?>">
          <input type="hidden" id="foto" value="<?php echo $this->HomeHelper()->getIssusers('images');?>">
          <input type="hidden" id="title_map" value="<?php echo $this->HomeHelper()->getIssusers('title');?>">
          <!-- <input type="hidden" id="mapPointX" value="">
          <input type="hidden" id="mapPointY" value=""> -->
        </div>
        <?= $this->inlineScript() ?>
       <!-- Scripts -->
       <?php echo $this->headScript()
            ->prependFile($this->basePath('/materialize_admin/assets/js/libs/sprintf/jquery.sprintf.js'))
            ->prependFile($this->basePath('/materialize_admin/assets/js/libs/inputmask/jquery.inputmask.bundle.min.js'))
            ->prependFile($this->basePath('/materialize_admin/assets/js/libs/remote-list/remote-list.js'))
            //  ->prependFile($this->basePath('/grupo-suricatis-admin/js/directions.js'))
            // ->prependFile('//maps.googleapis.com/maps/api/js?key=AIzaSyC-XOj2BxhA8H5sK97B8QXMGdxu22rHYWM')
            ->prependFile($this->basePath('/materialize_admin/js/jquery-3.1.0.min.js'))
            ->prependFile($this->basePath('/materialize_admin/js/modernizr-1.0.min.js'))?>
 <?php //echo $this->partial('/partial/home-button')?>
</body>
</html>